Header resp design
front-end-by-rimantas/8-grupe-portfolio-elvish pull request #70
Opened 2019-07-05 15:33 UTC by Valdasmo

#4

2019-07-05 18:18 UTC, belauzas requested changes

2019-07-05 18:18 UTC, belauzas commented on js/functions.js
> +function myFunction() {
Su tokiu funkcijos pavadinu gali kilti keblumų 😁

2019-07-07 20:43 UTC, Valdasmo commented on js/functions.js
> +function myFunction() {
matyt, reikės keisti pavadinimą...  Nors labai "originalus" buvo. :)

2019-07-08 15:38 UTC, ZilvinasLasauskas approved these changes

2019-07-08 15:39 UTC, merged